### ISSUE TITLE
Cannot find Analysis.Rmd

### ISSUE THREAD

**Issue by wulabupenn** [adamh-broad/single_cell_airway#1]
Hi,

I cannot find the file 'Analysis.Rmd' which was listed in the readme file.

Peng

**Comment by adamh-broad** [comment]
Ah, thanks for catching that!
It should be
"The easiest way to run it is to clone the repo (download ZIP button at top) and open the file ‘PulseSeq.Rmd' in RStudio. “

I’ve updated the repo. Please let me know if you have further questions!

Best,
Adam
